bool_list = bool([])
bool_string = bool("")
bool_int = bool(0)
bool_float = bool(0.0)
print("Boolean value of bool list is: ", bool(bool_list))
print("Boolean value of bool string is: ", bool(bool_string))
print("Boolean value of bool int is: ", bool(bool_int))
print("Boolean value of bool float is: ", bool(bool_float))